version: 1.0.{build}
image: Visual Studio 2022

# Environment variables
environment:
  VCPKG_ROOT: C:\vcpkg

install:
  # Install vcpkg
  - git clone https://github.com/microsoft/vcpkg.git %VCPKG_ROOT%
  - pushd %VCPKG_ROOT%
  - bootstrap-vcpkg.bat
  - popd

  # Install cppzmq (includes libzmq)
  - %VCPKG_ROOT%\vcpkg install cppzmq:x64-windows

  # Optional: integrate vcpkg with CMake automatically
  - %VCPKG_ROOT%\vcpkg integrate install

build: off

configuration: Debug

# Build the project
build_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . --config Debug
