version: 1.0.{build}
image: Visual Studio 2022

environment:
  VCPKG_ROOT: C:\vcpkg

install:
  - git clone https://github.com/microsoft/vcpkg.git %VCPKG_ROOT%
  - pushd %VCPKG_ROOT%
  - bootstrap-vcpkg.bat
  - popd
  - %VCPKG_ROOT%\vcpkg install cppzmq:x64-windows
  - %VCPKG_ROOT%\vcpkg integrate install

build: off
configuration: Debug

build_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug
  - cmake --build . --config Debug

after_build:
  - cd build
  - ctest --output-on-failure
