version: 1.0.{build}

image: Visual Studio 2022  # or another image with CMake and your compiler

build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 17 2022" ..
  - cmake --build . --config Release
